### ISSUE TITLE
Cannot scroll down secondary led color [Bridge4]

### ISSUE THREAD

**Issue by fourth44** [Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking#16]
- Device: Bridge4
 - Firmware version: v1.0.1beta2
 - Hardware version: v1.0.1

Switches / Config / secondary led colour: 
Can only scroll colours up, but not down.

Primary led colour is not affected.

**Comment by samspencer5991** [comment]
Fixed with latest release

**Comment by fourth44** [comment]
Still not fixed! It's different per primary mode I discovered.
It does work fine for primary modes toggle, momentary, tap tempo. The bug exists for sequential, sequential linked, scrolling, scrolling linked. 

Scrolling down primary color in 'scrolling linked' did get fixed.
